/**
 * Free-text to icon-name matching.
 *
 * Kept apart from the drawings so icons.js stays a picture library: this file
 * is only about the many words a depot admin might type for the same thing.
 */

/** Friendly aliases so seeded/legacy icon names still resolve. */
export const ALIASES = {
  droplets: 'droplet',
  water: 'droplet',
  washer: 'pressure-washer',
  'power-washer': 'pressure-washer',
  lawn: 'lawn-mower',
  mow: 'lawn-mower',
  mower: 'lawn-mower',
  'push-mower': 'lawn-mower',
  'walk-behind-mower': 'lawn-mower',
  'ride-on-mower': 'riding-mower',
  garden: 'garden-cart',
  'hand-tools': 'tools',
  'power-tools': 'drill',
  trimmer: 'hedge-trimmer',
  'weed-eater': 'string-trimmer',
  'weed-whacker': 'string-trimmer',
  strimmer: 'string-trimmer',
  'line-trimmer': 'string-trimmer',
  edger: 'lawn-edger',
  blower: 'leaf-blower',
  saw: 'chainsaw',
  sawzall: 'reciprocating-saw',
  'chop-saw': 'miter-saw',
  'cut-off-saw': 'concrete-saw',
  'tile-saw': 'concrete-saw',
  'skill-saw': 'circular-saw',
  grinder: 'angle-grinder',
  'orbital-sander': 'sander',
  'belt-sander': 'sander',
  'drywall-sander': 'pole-sander',
  'impact-driver': 'drill',
  'cordless-drill': 'drill',
  'multi-tool': 'rotary-tool',
  'oscillating-tool': 'rotary-tool',
  breaker: 'jackhammer',
  'demolition-hammer': 'jackhammer',
  'demo-hammer': 'jackhammer',
  'airless-sprayer': 'paint-sprayer',
  'texture-sprayer': 'paint-sprayer',
  sprayer: 'paint-sprayer',
  'paint-gun': 'paint-sprayer',
  generator: 'engine',
  genset: 'generator',
  motor: 'engine',
  fuel: 'gas-station',
  gas: 'gas-station',
  petrol: 'gas-station',
  'jerry-can': 'gas-can',
  'fuel-can': 'gas-can',
  propane: 'propane-tank',
  battery: 'tool-battery',
  charger: 'battery-charger',
  compressor: 'air-compressor',
  rake: 'rake',
  spade: 'shovel',
  'a-frame-ladder': 'step-ladder',
  'stepladder': 'step-ladder',
  cleaning: 'vacuum',
  'carpet-machine': 'carpet-extractor',
  'carpet-cleaner': 'carpet-extractor',
  extractor: 'carpet-extractor',
  'floor-buffer': 'floor-scrubber',
  polisher: 'floor-scrubber',
  buffer: 'floor-scrubber',
  'shop-vac': 'shop-vacuum',
  'wet-dry-vacuum': 'shop-vacuum',
  'wet-vac': 'shop-vacuum',
  hoover: 'upright-vacuum',
  'carpet-dryer': 'air-mover',
  'blower-fan': 'air-mover',
  'air-blower': 'air-mover',
  'sump-pump': 'water-pump',
  'trash-pump': 'water-pump',
  auger: 'drain-snake',
  snake: 'drain-snake',
  dolly: 'hand-truck',
  'hand-cart': 'hand-truck',
  'boom-lift': 'scissor-lift',
  'man-lift': 'scissor-lift',
  safety: 'hard-hat',
  ppe: 'hard-hat',
  access: 'ladder',
  dashboard: 'home',
  catalog: 'grid',
  requests: 'clipboard',
  approvals: 'check-circle',
  loans: 'handshake',
  tickets: 'ticket',
  maintenance: 'wrench',
  inventory: 'boxes',
  capex: 'chart',
  audit: 'history',
  it: 'shield',
  cross: 'x',
  close: 'x',
  warning: 'alert',
  ok: 'check',
  spanner: 'wrench',
  cog: 'settings',
  gear: 'settings',
  profile: 'user',
  signout: 'logout',
  barcode: 'qr',
  print: 'qr',
  pdf: 'file',
  excel: 'file',
  manual: 'book',
  photo: 'camera',
  image: 'camera',
  location: 'pin',
  property: 'building',
};

/**
 * Words we look for in a category or tool name when nobody picked an icon.
 * Most specific first: "riding mower" must beat plain "mower".
 */
export const KEYWORDS = [
  // Two-word names first so "riding mower" beats plain "mower".
  ['riding mower', 'riding-mower'],
  ['ride on mower', 'riding-mower'],
  ['zero turn', 'zero-turn-mower'],
  ['push mower', 'lawn-mower'],
  ['walk behind', 'lawn-mower'],
  ['pressure washer', 'pressure-washer'],
  ['power washer', 'pressure-washer'],
  ['hedge trim', 'hedge-trimmer'],
  ['string trim', 'string-trimmer'],
  ['line trim', 'string-trimmer'],
  ['weed eater', 'string-trimmer'],
  ['weed whack', 'string-trimmer'],
  ['pole saw', 'pole-saw'],
  ['leaf blow', 'leaf-blower'],
  ['backpack blow', 'backpack-blower'],
  ['snow blow', 'snow-blower'],
  ['wood chip', 'wood-chipper'],
  ['backpack spray', 'backpack-sprayer'],
  ['paint spray', 'paint-sprayer'],
  ['airless', 'paint-sprayer'],
  ['texture spray', 'paint-sprayer'],
  ['paint roll', 'paint-roller'],
  ['paint brush', 'paint-brush'],
  ['paint bucket', 'paint-bucket'],
  ['caulk', 'caulk-gun'],
  ['carpet extract', 'carpet-extractor'],
  ['carpet clean', 'carpet-extractor'],
  ['carpet machine', 'carpet-extractor'],
  ['carpet dry', 'air-mover'],
  ['air mover', 'air-mover'],
  ['floor scrub', 'floor-scrubber'],
  ['floor buff', 'floor-scrubber'],
  ['floor polish', 'floor-scrubber'],
  ['wet dry', 'shop-vacuum'],
  ['wet/dry', 'shop-vacuum'],
  ['shop vac', 'shop-vacuum'],
  ['upright vac', 'upright-vacuum'],
  ['steam clean', 'steam-cleaner'],
  ['mop bucket', 'mop-bucket'],
  ['drain snake', 'drain-snake'],
  ['drain auger', 'drain-snake'],
  ['circular saw', 'circular-saw'],
  ['skill saw', 'circular-saw'],
  ['reciprocating', 'reciprocating-saw'],
  ['sawzall', 'reciprocating-saw'],
  ['miter saw', 'miter-saw'],
  ['mitre saw', 'miter-saw'],
  ['chop saw', 'miter-saw'],
  ['table saw', 'table-saw'],
  ['tile saw', 'concrete-saw'],
  ['concrete saw', 'concrete-saw'],
  ['cut off saw', 'concrete-saw'],
  ['angle grind', 'angle-grinder'],
  ['pole sand', 'pole-sander'],
  ['drywall sand', 'pole-sander'],
  ['orbital sand', 'sander'],
  ['belt sand', 'sander'],
  ['nail gun', 'nail-gun'],
  ['brad nail', 'nail-gun'],
  ['framing nail', 'nail-gun'],
  ['heat gun', 'heat-gun'],
  ['rotary tool', 'rotary-tool'],
  ['oscillating', 'rotary-tool'],
  ['impact driver', 'drill'],
  ['hammer drill', 'hammer-drill'],
  ['rotary hammer', 'jackhammer'],
  ['demolition hammer', 'jackhammer'],
  ['demo hammer', 'jackhammer'],
  ['jack hammer', 'jackhammer'],
  ['concrete mix', 'concrete-mixer'],
  ['cement mix', 'concrete-mixer'],
  ['plate compact', 'plate-compactor'],
  ['gas can', 'gas-can'],
  ['fuel can', 'gas-can'],
  ['jerry can', 'gas-can'],
  ['propane', 'propane-tank'],
  ['air compress', 'air-compressor'],
  ['extension cord', 'extension-cord'],
  ['work light', 'work-light'],
  ['light tower', 'work-light'],
  ['tool battery', 'tool-battery'],
  ['battery charg', 'battery-charger'],
  ['pipe wrench', 'pipe-wrench'],
  ['sump pump', 'water-pump'],
  ['trash pump', 'water-pump'],
  ['water pump', 'water-pump'],
  ['step ladder', 'step-ladder'],
  ['stepladder', 'step-ladder'],
  ['a frame', 'step-ladder'],
  ['extension ladder', 'extension-ladder'],
  ['scissor lift', 'scissor-lift'],
  ['boom lift', 'scissor-lift'],
  ['man lift', 'scissor-lift'],
  ['hand truck', 'hand-truck'],
  ['pallet jack', 'pallet-jack'],
  ['laser level', 'laser-level'],
  ['tape measure', 'tape-measure'],
  ['tool belt', 'tool-belt'],
  ['hard hat', 'hard-hat'],
  ['first aid', 'first-aid'],
  ['air condition', 'air-conditioning'],
  ['gas station', 'gas-station'],

  // Single words.
  ['mower', 'lawn-mower'],
  ['tiller', 'tiller'],
  ['tractor', 'tractor'],
  ['spreader', 'spreader'],
  ['chainsaw', 'chainsaw'],
  ['edger', 'lawn-edger'],
  ['blower', 'leaf-blower'],
  ['trimmer', 'hedge-trimmer'],
  ['chipper', 'wood-chipper'],
  ['wheelbarrow', 'wheelbarrow'],
  ['rake', 'rake'],
  ['squeegee', 'squeegee'],
  ['plunger', 'plunger'],
  ['dehumidifier', 'dehumidifier'],
  ['extractor', 'carpet-extractor'],
  ['scrubber', 'floor-scrubber'],
  ['buffer', 'floor-scrubber'],
  ['vacuum', 'shop-vacuum'],
  ['washer', 'pressure-washer'],
  ['jackhammer', 'jackhammer'],
  ['breaker', 'jackhammer'],
  ['compactor', 'plate-compactor'],
  ['sledge', 'sledgehammer'],
  ['grinder', 'angle-grinder'],
  ['sander', 'sander'],
  ['jigsaw', 'jigsaw'],
  ['welder', 'welder'],
  ['welding', 'welder'],
  ['multimeter', 'multimeter'],
  ['generator', 'generator'],
  ['scaffold', 'scaffold'],
  ['ladder', 'ladder'],
  ['dolly', 'hand-truck'],
  ['sprayer', 'paint-sprayer'],
  ['roller', 'paint-roller'],
  ['paint', 'paint-bucket'],
  ['drill', 'drill'],
  ['saw', 'chainsaw'],
  ['engine', 'engine'],
  ['compressor', 'air-compressor'],
  ['pump', 'water-pump'],
  ['shovel', 'shovel'],
  ['spade', 'shovel'],
  ['fork', 'pitchfork'],
  ['pickaxe', 'pickaxe'],
  ['axe', 'axe'],
  ['hammer', 'hammer'],
  ['wrench', 'pipe-wrench'],
  ['spanner', 'wrench'],
  ['screwdriver', 'tools'],
  ['plier', 'tools'],
  ['blade', 'blade'],
  ['knife', 'knife'],
  ['scissor', 'scissors'],
  ['shear', 'scissors'],
  ['ruler', 'ruler'],
  ['level', 'laser-level'],
  ['brush', 'paint-brush'],
  ['spray', 'spray-can'],
  ['bucket', 'bucket'],
  ['mop', 'mop-bucket'],
  ['clean', 'shop-vacuum'],
  ['wash', 'wash'],
  ['hose', 'pressure-washer'],
  ['water', 'droplet'],
  ['fuel', 'gas-can'],
  ['gas', 'gas-can'],
  ['battery', 'tool-battery'],
  ['charger', 'battery-charger'],
  ['cord', 'extension-cord'],
  ['electric', 'plug'],
  ['light', 'work-light'],
  ['lamp', 'bulb'],
  ['torch', 'torch'],
  ['heater', 'flame'],
  ['fan', 'air-mover'],
  ['snow', 'snowflake'],
  ['cart', 'garden-cart'],
  ['trolley', 'hand-truck'],
  ['trailer', 'trailer'],
  ['truck', 'truck'],
  ['forklift', 'forklift'],
  ['lift', 'scissor-lift'],
  ['crane', 'crane'],
  ['fence', 'fence'],
  ['tree', 'tree'],
  ['plant', 'plant'],
  ['garden', 'garden-cart'],
  ['lawn', 'lawn-mower'],
  ['landscape', 'lawn-mower'],
  ['safety', 'hard-hat'],
  ['helmet', 'helmet'],
  ['glove', 'hard-hat'],
  ['mask', 'face-mask'],
  ['glasses', 'glasses'],
  ['barrel', 'barrel'],
  ['tank', 'propane-tank'],
  ['hand tool', 'tools'],
  ['power tool', 'drill'],
  ['tool', 'tools'],
];
